TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: "no"
  eval_steps: 500
  gradient_accumulation_steps: 16
  eval_accumulation_steps: 1
  predict_with_generate: True
  eval_dataset_dimension: 15
