artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/NicolaCortinovis/Demo-repo/raw/main/qag_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt 
  ALL_REQUIRED_FILES: ["train.jsonl", "test.jsnol", "validation.jsnol"]