name: Secrets

on:
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "This is a test for the secret ${{secrets.HUGGINGFACE_API_TOKEN}}"
