name: Secrets

on:
  workflow_dispatch

jobs:
  top-secret:
    runs_on: ubuntu-latest
    env:

    steps:
      -name: Test
      -run: echo "This is a test for the secret ${{secrets.HUGGINGFACE_API_TOKEN}}"
